services:
  app:
    build:
      context: ./docker/php
    container_name: laravel_app
    working_dir: /var/www
    volumes:
      - ./weather-api:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - laravel

  webserver:
    image: nginx:stable-alpine
    container_name: laravel_webserver
    working_dir: /var/www
    volumes:
      - ./weather-api:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    networks:
      - laravel
    depends_on:
      - app

  # db:
  #   image: mariadb:10.5
  #   container_name: laravel_db
  #   environment:
  #     MYSQL_DATABASE: laravel
  #     MYSQL_ROOT_PASSWORD: secret
  #     MYSQL_USER: user
  #     MYSQL_PASSWORD: secret
  #   ports:
  #     - "3306:3306"
  #   networks:
  #     - laravel
  #   volumes:
  #     - dbdata:/var/lib/mysql

networks:
  laravel:
    driver: bridge

volumes:
  dbdata:
